sed -i 's/Ã /à/g' oweia_10.sql
sed -i 's/Ã¢/â/g' oweia_10.sql
sed -i 's/Ã©/é/g' oweia_10.sql
sed -i 's/Ã¨/è/g' oweia_10.sql
sed -i 's/Ãª/ê/g' oweia_10.sql
sed -i 's/Ã«/ë/g' oweia_10.sql
sed -i 's/Ã®/î/g' oweia_10.sql
sed -i 's/Ã¯/ï/g' oweia_10.sql
sed -i 's/Ã´/ô/g' oweia_10.sql
sed -i 's/Ã¶/ö/g' oweia_10.sql
sed -i 's/Ã¹/ù/g' oweia_10.sql
sed -i 's/Ã»/û/g' oweia_10.sql
sed -i 's/Ã¼/ü/g' oweia_10.sql
sed -i 's/Ã§/ç/g' oweia_10.sql
sed -i 's/Å“/œ/g' oweia_10.sql
sed -i 's/â¬/€/g' oweia_10.sql
sed -i 's/Â°/°/g' oweia_10.sql
sed -i 's/Ã/À/g' oweia_10.sql
sed -i 's/Ã/Â/g' oweia_10.sql
sed -i 's/Ã/É/g' oweia_10.sql
sed -i 's/Ã/È/g' oweia_10.sql
sed -i 's/Ã/Ê/g' oweia_10.sql
sed -i 's/Ã/Ë/g' oweia_10.sql
sed -i 's/Ã/Î/g' oweia_10.sql
sed -i 's/Ã/Ï/g' oweia_10.sql
sed -i 's/Ã/Ô/g' oweia_10.sql
sed -i 's/Ã/Ö/g' oweia_10.sql
sed -i 's/Ã/Ù/g' oweia_10.sql
sed -i 's/Ã/Û/g' oweia_10.sql
sed -i 's/Ã/Ü/g' oweia_10.sql
sed -i 's/Ã/Ç/g' oweia_10.sql
sed -i 's/Å/Œ/g' oweia_10.sql
sed -i 's/Å/Œ/g' oweia_10.sql
sed -i 's/â€™/’/g' oweia_10.sql
sed -i 's/Â«/«/g' oweia_10.sql
sed -i 's/Â»/»/g' oweia_10.sql
