sed -i 's/Ã /à/g' $1
sed -i 's/Ã¢/â/g' $1
sed -i 's/Ã©/é/g' $1
sed -i 's/Ã¨/è/g' $1
sed -i 's/Ãª/ê/g' $1
sed -i 's/Ã«/ë/g' $1
sed -i 's/Ã®/î/g' $1
sed -i 's/Ã¯/ï/g' $1
sed -i 's/Ã´/ô/g' $1
sed -i 's/Ã¶/ö/g' $1
sed -i 's/Ã¹/ù/g' $1
sed -i 's/Ã»/û/g' $1
sed -i 's/Ã¼/ü/g' $1
sed -i 's/Ã§/ç/g' $1
sed -i 's/Å“/œ/g' $1
sed -i 's/â,¬/€/g' $1
sed -i 's/Â°/°/g' $1
#sed -i 's/Ã/À/g' $1
#sed -i 's/Ã/Â/g' $1
#sed -i 's/Ã/É/g' $1
#sed -i 's/Ã/È/g' $1
#sed -i 's/Ã/Ê/g' $1
#sed -i 's/Ã/Ë/g' $1
#sed -i 's/Ã/Î/g' $1
#sed -i 's/Ã/Ï/g' $1
#sed -i 's/Ã/Ô/g' $1
#sed -i 's/Ã/Ö/g' $1
#sed -i 's/Ã/Ù/g' $1
#sed -i 's/Ã/Û/g' $1
#sed -i 's/Ã/Ü/g' $1
#sed -i 's/Ã/Ç/g' $1
#sed -i 's/Å/Œ/g' $1
#sed -i 's/Å/Œ/g' $1
sed -i 's/â€™/’/g' $1
sed -i 's/Â«/«/g' $1
sed -i 's/Â»/»/g' $1
